/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from 'three'


export function Character2(props) {
  const texture = useTexture('/images/SirYakari_with_clothes_by_SirYakari.png', (texture) => {
    console.log(texture)
    texture.magFilter = THREE.NearestFilter;
    texture.version = 8;
  })
  const customMaterial = new THREE.MeshBasicMaterial({
      map: texture,
      transparent: true,
      side: THREE.FrontSide
  })

  const { nodes, materials } = useGLTF("/character_modded.glb");
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.Body} />
      <skinnedMesh
        geometry={nodes.Player.geometry}
        material={customMaterial}
        skeleton={nodes.Player.skeleton}
      />
    </group>
  );
}

useGLTF.preload("/character_modded.glb");

